# Generated by Django 5.1.4 on 2026-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        help_text="Main App Fee Waiver address. Used wherever a specific address below is left blank.",
                        max_length=254,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="General inquiries.", max_length=254
                    ),
                ),
                (
                    "cv_review_email",
                    models.EmailField(
                        blank=True,
                        help_text="Where members send CVs for review.",
                        max_length=254,
                    ),
                ),
                (
                    "sop_review_email",
                    models.EmailField(
                        blank=True,
                        help_text="Where members send SOPs for review.",
                        max_length=254,
                    ),
                ),
                (
                    "appointment_email",
                    models.EmailField(
                        blank=True,
                        help_text="Where appointment requests go.",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        help_text="Account / technical support.",
                        max_length=254,
                    ),
                ),
                (
                    "partnership_email",
                    models.EmailField(
                        blank=True,
                        help_text="Partnerships and collaborations.",
                        max_length=254,
                    ),
                ),
                (
                    "member_count_display",
                    models.CharField(
                        default="2,000+",
                        help_text="Community size shown on the site (the wider community, not only website accounts).",
                        max_length=30,
                    ),
                ),
                (
                    "community_group_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. 'App Fee Waiver WhatsApp Group'.",
                        max_length=80,
                    ),
                ),
                (
                    "community_group_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional invite link. The 'Join Our Group' card only appears when this is set.",
                    ),
                ),
                (
                    "announcement_banner",
                    models.CharField(
                        blank=True,
                        help_text="Optional short message shown at the top of every page.",
                        max_length=200,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
