# Generated by Django 5.1.4 on 2026-09-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="auto_hide_report_count",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Hide a post or comment automatically once this many different members report it. 0 = off.",
                verbose_name="auto-hide after this many reports",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="hold_links_from_new_members",
            field=models.BooleanField(
                default=True,
                help_text="Posts/comments with links from members with no approved posts yet wait for approval.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="new_member_review_posts",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="A member's first N posts wait for moderator approval. Set 0 to turn this off.",
                verbose_name="review new members' first posts",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="scam_filter_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Posts, comments and opportunities containing the phrases below wait for approval.",
                verbose_name="hold posts with scam wording",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="scam_phrases",
            field=models.TextField(
                blank=True,
                default="processing fee\nregistration fee\npay a fee\npay the fee\nsend money\ntransfer money\nwestern union\nmoneygram\ngift card\nbitcoin\nguaranteed admission\nguaranteed scholarship\n100% guaranteed\nagent fee\nvisa guaranteed\ndm me for\ninbox me\nwhatsapp me\nbank details\naccount number",
                help_text="One phrase per line (not case-sensitive). WhatsApp and Telegram links are always checked.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_scam_warning",
            field=models.BooleanField(
                default=True,
                help_text="Show a 'we never ask you to pay' warning on every community post.",
            ),
        ),
    ]
