# Generated by Django 5.1.4 on 2026-09-25 14:07

from django.db import migrations, models


def keep_contact_email(apps, schema_editor):
    """Carry the old primary email over to contact_email before the old fields are removed."""
    SiteSettings = apps.get_model("core", "SiteSettings")
    for row in SiteSettings.objects.all():
        if not row.contact_email and row.primary_email:
            row.contact_email = row.primary_email
            row.save(update_fields=["contact_email"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sitesettings_auto_hide_report_count_and_more"),
    ]

    operations = [
        migrations.RunPython(keep_contact_email, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="sitesettings",
            name="announcement_banner",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="appointment_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="auto_hide_report_count",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="community_group_name",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="community_group_url",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="cv_review_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hold_links_from_new_members",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="member_count_display",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="new_member_review_posts",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="partnership_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="primary_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="scam_filter_enabled",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="scam_phrases",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="show_scam_warning",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="sop_review_email",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="support_email",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="community_free_answer",
            field=models.TextField(
                blank=True,
                help_text="Write your actual policy. The question is hidden on the site while this is empty.",
                verbose_name="answer to “Is the community free?”",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="displayed_member_count",
            field=models.CharField(
                default="2,000+",
                help_text="Shown in the headline and stats, e.g. 2,000+",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="homepage_announcement",
            field=models.CharField(
                blank=True,
                help_text="Optional one-line message shown at the top of the site.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram_url",
            field=models.URLField(blank=True, verbose_name="Instagram URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="linkedin_url",
            field=models.URLField(blank=True, verbose_name="LinkedIn URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registration_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Untick to pause new registrations (the form is replaced by a short notice).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="App Fee Waiver", max_length=80),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimony_form_url",
            field=models.URLField(
                blank=True,
                help_text="Opens when people click “Submit My Testimony”.",
                verbose_name="Google testimony form URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimony_sync_interval_minutes",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="How often the site checks the Google Sheet for newly approved testimonies.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="testimony_sync_url",
            field=models.URLField(
                blank=True,
                help_text="The web-app URL from docs/GOOGLE_SHEET_SETUP.md. Only approved rows are imported.",
                verbose_name="Google Apps Script sync URL",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="x_url",
            field=models.URLField(blank=True, verbose_name="X (Twitter) URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="YouTube URL"),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                default="appfeewaiver@gmail.com",
                help_text="Shown on the site for questions and registration problems.",
                max_length=254,
            ),
        ),
    ]
