# Generated by Django 5.1.4 on 2026-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_sitesettings_announcement_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="testimony_form_url",
            field=models.URLField(
                blank=True,
                help_text="Opens when people click “Share Your Story” on the Funding Testimonies page.",
                verbose_name="Google testimony form URL",
            ),
        ),
    ]
