# Generated by Django 5.1.4 on 2026-09-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("scam", "Scam"),
                            ("incorrect", "Incorrect information"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate content"),
                            ("duplicate", "Duplicate post"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("dismissed", "Dismissed"),
                            ("actioned", "Action taken"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=255)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.post",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_report", "Can review reports and moderate content")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("comment__isnull", True), ("post__isnull", False)
                            ),
                            models.Q(
                                ("comment__isnull", False), ("post__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="report_targets_exactly_one_item",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("post__isnull", False), ("status", "open")),
                        fields=("reporter", "post"),
                        name="one_open_report_per_post_per_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("comment__isnull", False), ("status", "open")
                        ),
                        fields=("reporter", "comment"),
                        name="one_open_report_per_comment_per_user",
                    ),
                ],
            },
        ),
    ]
