# Generated by Django 5.1.4 on 2026-09-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OpportunityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                (
                    "short_label",
                    models.CharField(
                        help_text="Upper-case label for badges, e.g. SCHOLARSHIP.",
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "organization",
                    models.CharField(
                        max_length=200, verbose_name="university / organization"
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=80)),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("postdoctoral", "Postdoctoral"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(default="Any field", max_length=150),
                ),
                (
                    "funding_type",
                    models.CharField(
                        choices=[
                            ("fully_funded", "Fully funded"),
                            ("partially_funded", "Partially funded"),
                            ("tuition_waiver", "Tuition waiver"),
                            ("stipend", "Stipend / salary"),
                            ("fee_waiver", "Application fee waiver"),
                            ("not_specified", "Not specified"),
                        ],
                        db_index=True,
                        default="not_specified",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "deadline_note",
                    models.CharField(
                        blank=True,
                        help_text="Optional, e.g. 'Rolling' or 'Varies by program'.",
                        max_length=80,
                    ),
                ),
                ("description", models.TextField(max_length=5000)),
                ("eligibility", models.TextField(blank=True, max_length=3000)),
                ("additional_info", models.TextField(blank=True, max_length=3000)),
                (
                    "official_source_url",
                    models.URLField(max_length=500, verbose_name="official source URL"),
                ),
                (
                    "application_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="application URL"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Community Submitted"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected (hidden)"),
                        ],
                        db_index=True,
                        default="submitted",
                        max_length=12,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(
                        blank=True,
                        help_text="Internal note for moderators.",
                        max_length=255,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opportunity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="opportunities.opportunitytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "opportunities",
                "ordering": ["-created_at"],
                "permissions": [
                    ("verify_opportunity", "Can verify or reject opportunities")
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "saved opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["status", "-created_at"], name="opportuniti_status_175007_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["opportunity_type", "status"],
                name="opportuniti_opportu_61c48d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedopportunity",
            constraint=models.UniqueConstraint(
                fields=("user", "opportunity"), name="unique_saved_opportunity"
            ),
        ),
    ]
