# Generated by Django 5.1.4 on 2026-09-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WhatsAppGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For your reference, e.g. Community Group 1.",
                        max_length=80,
                    ),
                ),
                (
                    "invite_link",
                    models.URLField(
                        help_text="The WhatsApp invite link, e.g. https://chat.whatsapp.com/…",
                        max_length=300,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop sending new people here.",
                        verbose_name="active",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional. Stop assigning website registrations once this many have been sent here.",
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Tie-breaker: lower numbers are used first.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "WhatsApp group",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CommunityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("country", models.CharField(db_index=True, max_length=80)),
                (
                    "current_level",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("masters", "Master's"),
                            ("phd", "PhD"),
                            ("postdoctoral", "Postdoctoral"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(blank=True, max_length=150)),
                (
                    "whatsapp_link_sent",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("email_attempts", models.PositiveSmallIntegerField(default=0)),
                ("email_error", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "last_requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this email address submitted the form.",
                        null=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "whatsapp_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Change this to move the person to another group, then use “Resend WhatsApp email”.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registrations",
                        to="registrations.whatsappgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "registration",
                "ordering": ["-created_at"],
            },
        ),
    ]
