# Generated by Django 5.1.4 on 2026-09-25 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Part of the web address. Filled in automatically from the title.",
                        max_length=220,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scholarship", "Scholarships"),
                            ("fee_waiver", "Application Fee Waivers"),
                            ("fellowship", "Fellowships"),
                            ("internship", "Internships"),
                            ("admissions", "Admissions"),
                            ("tips", "Tips & Guides"),
                            ("other", "Other"),
                        ],
                        default="scholarship",
                        max_length=20,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for cards. Leave empty to use the start of the post.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text. Leave a blank line between paragraphs. Web links become clickable."
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional. A public image link (e.g. from your website or Google Drive).",
                        max_length=500,
                        verbose_name="cover image link",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True,
                        help_text="Optional application deadline, shown on the post.",
                        null=True,
                    ),
                ),
                (
                    "apply_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to the official opportunity page.",
                        max_length=500,
                        verbose_name="official link",
                    ),
                ),
                ("published", models.BooleanField(db_index=True, default=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Posts dated in the future stay hidden until then.",
                    ),
                ),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "blog post",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cv", "CV / Resume"),
                            ("sop", "Statement of Purpose"),
                            ("personal", "Personal Statement"),
                            ("recommendation", "Recommendation Letters"),
                            ("email", "Emails to Professors"),
                            ("other", "Other"),
                        ],
                        default="cv",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "link",
                    models.URLField(
                        help_text="Google Drive / Google Docs link with sharing set to “Anyone with the link can view”.",
                        max_length=500,
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True,
                        help_text="Button text. Default: “Open”.",
                        max_length=40,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower numbers are shown first."
                    ),
                ),
                ("published", models.BooleanField(db_index=True, default=True)),
                ("is_demo", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "order", "title"],
            },
        ),
    ]
