# Generated by Django 5.1.4 on 2026-09-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                ("trigger", models.CharField(default="auto", max_length=20)),
                ("rows_received", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "sync log",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the Google Sheet row this came from (blank for testimonies added by hand).",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Private. Never shown on the website.",
                        max_length=254,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="degree / program"
                    ),
                ),
                ("university", models.CharField(blank=True, max_length=150)),
                ("country", models.CharField(blank=True, max_length=80)),
                (
                    "success_type",
                    models.CharField(
                        choices=[
                            ("fully_funded", "Fully Funded"),
                            ("scholarship", "Scholarship"),
                            ("admission", "Admission"),
                            ("fee_waiver", "Application Fee Waiver"),
                            ("assistantship", "Assistantship"),
                            ("fellowship", "Fellowship"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("testimony", models.TextField(max_length=2000)),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional public image link.",
                        max_length=500,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("published", models.BooleanField(db_index=True, default=True)),
                (
                    "featured",
                    models.BooleanField(
                        default=False, help_text="Featured testimonies are shown first."
                    ),
                ),
                (
                    "keep_admin_edits",
                    models.BooleanField(
                        default=False,
                        help_text="Ticked automatically when you edit this in Admin, so the Google Sheet sync won't overwrite your changes.",
                    ),
                ),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False, help_text="Sample data for local testing only."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "testimonies",
                "ordering": ["-featured", "-submitted_at", "-created_at"],
            },
        ),
    ]
