# Generated by Django 5.1.4 on 2026-09-23 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "resource categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("guide", "Guide"),
                            ("link", "External link"),
                            ("template", "Template"),
                            ("checklist", "Checklist"),
                        ],
                        default="guide",
                        max_length=12,
                        verbose_name="resource type",
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        help_text="Plain text. Blank lines start new paragraphs. For checklists, start each item on its own line with '- '.",
                    ),
                ),
                ("external_url", models.URLField(blank=True, max_length=500)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Shown in Quick Resources on the homepage.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-published_at"],
            },
        ),
    ]
